#!/usr/bin/env python3
"""build-toc.py — 從 book.pdf 的 outline 抽實際頁碼，和 chapters.yml 合併，產生 _toc-data.typ

Usage:
    python3 scripts/build-toc.py

Output:
    _toc-data.typ   (Typst data module, toc.qmd 會 import)

Pipeline:
    1. `mutool show _book/book.pdf outline` → 抓所有 level-1 標題 + 頁碼
    2. 載入 chapters.yml 的 15 章主清單
    3. 標題比對：能對上 → status="pilot" + page 為 PDF 實際頁；對不上 → status="planned" no page
    4. 寫出 _toc-data.typ 供 toc.qmd 讀

為什麼不直接 hand-write toc.qmd：
    因為頁碼會在每次重排後改變，hand-write 會失準。
    mutool outline 是 Typst 自動從 H1 產的，是唯一的事實來源。
"""
from __future__ import annotations
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    sys.exit("需要 PyYAML: uv pip install pyyaml 或 pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
BOOK_PDF = ROOT / "_book" / "book.pdf"
CHAPTERS_YAML = ROOT / "chapters.yml"
OUTPUT = ROOT / "_toc-data.typ"


def extract_outline_pages(pdf_path: Path) -> dict[str, int]:
    """Return {heading_title: physical_page_1_indexed} from PDF outline (level-1 only)."""
    if not pdf_path.exists():
        sys.exit(f"找不到 {pdf_path}，先 `quarto render book.qmd`")

    result = subprocess.run(
        ["mutool", "show", str(pdf_path), "outline"],
        capture_output=True, text=True, check=True,
    )
    # mutool format:
    # +	"前言"	#page=1&zoom=...
    # |		"sub heading"	#page=...
    # + 開頭表示展開的節點（level-1 章）
    # | 接著 tab 越多層越深
    # 我們只要 level-1：行首 + 或 - 且 tab 數最少（1 個）
    headings: dict[str, int] = {}
    for line in result.stdout.splitlines():
        # level-1 的特徵：行首 [+-] + 一個 tab + "Title" + tab + #page=N
        m = re.match(r'^[+\-]\t"([^"]+)"\s+#page=(\d+)', line)
        if m:
            title, page = m.group(1), int(m.group(2))
            headings[title] = page
    return headings


def load_chapters(yaml_path: Path) -> list[dict]:
    data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    return data["parts"]


def typst_escape(s: str) -> str:
    """Escape double quotes and backslashes for Typst string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_typst_data(parts: list[dict], pdf_headings: dict[str, int]) -> str:
    """Emit Typst module with toc entries."""
    lines = [
        "// Auto-generated by scripts/build-toc.py — DO NOT EDIT by hand.",
        "// Source of truth: chapters.yml (structure) + _book/book.pdf outline (actual pages).",
        "",
        "#let toc-parts = (",
    ]
    for part in parts:
        lines.append(f'  (')
        lines.append(f'    name: "{typst_escape(part["name"])}",')
        lines.append(f'    chapters: (')
        for ch in part["chapters"]:
            title = ch["title"]
            page = pdf_headings.get(title)
            if page is not None:
                status = "pilot"
                page_str = str(page)
            else:
                status = "planned"
                page_str = "none"
            lines.append("      (")
            lines.append(f'        num: "{ch["num"]}.",')
            lines.append(f'        title: "{typst_escape(title)}",')
            lines.append(f'        subtitle: "{typst_escape(ch["subtitle"])}",')
            lines.append(f'        status: "{status}",')
            lines.append(f'        page: {page_str},')
            lines.append("      ),")
        lines.append(f'    ),')
        lines.append(f'  ),')
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    pdf_headings = extract_outline_pages(BOOK_PDF)
    parts = load_chapters(CHAPTERS_YAML)

    # 稽核報告：哪些章在 PDF 找到了、哪些沒找到
    expected_titles = {ch["title"] for part in parts for ch in part["chapters"]}
    found = set(pdf_headings) & expected_titles
    missing_from_pdf = expected_titles - set(pdf_headings)
    unexpected_in_pdf = set(pdf_headings) - expected_titles

    print(f"PDF outline 共 {len(pdf_headings)} 個 level-1 標題")
    print(f"章節主檔共 {len(expected_titles)} 章")
    print(f"✓ 對上（pilot，帶頁碼）: {len(found)}")
    for t in sorted(found):
        print(f"  · {t} → p.{pdf_headings[t]}")
    print(f"⧗ 對不上（planned，無頁碼）: {len(missing_from_pdf)}")
    for t in sorted(missing_from_pdf):
        print(f"  · {t}")
    if unexpected_in_pdf:
        print(f"⚠ PDF 有但不在 chapters.yml 的 outline: {len(unexpected_in_pdf)}")
        for t in sorted(unexpected_in_pdf):
            print(f"  · {t}  (非章節頁首？例如 前言 / 參考文獻)")

    OUTPUT.write_text(render_typst_data(parts, pdf_headings), encoding="utf-8")
    print(f"\n已寫入 {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
